[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
jailbreak_pool = "2wQ3soEMzS2rNuJskGWt3Ty8HWAjee4fhUFVCJ5aCs6j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
